submitit ERROR (2023-09-17 03:01:17,226) - Submitted job triggered an exception
Traceback (most recent call last):
  File "/mnt/sw/nix/store/fyb44x0iw8gg9dc8bx70ykh1pbrzfgfv-python-3.10.8-view/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/sw/nix/store/fyb44x0iw8gg9dc8bx70ykh1pbrzfgfv-python-3.10.8-view/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/home/blyo1/venvs/jupyter-gpu/lib/python3.10/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/mnt/home/blyo1/venvs/jupyter-gpu/lib/python3.10/site-packages/submitit/core/submission.py", line 72, in submitit_main
    process_job(args.folder)
  File "/mnt/home/blyo1/venvs/jupyter-gpu/lib/python3.10/site-packages/submitit/core/submission.py", line 65, in process_job
    raise error
  File "/mnt/home/blyo1/venvs/jupyter-gpu/lib/python3.10/site-packages/submitit/core/submission.py", line 54, in process_job
    result = delayed.result()
  File "/mnt/home/blyo1/venvs/jupyter-gpu/lib/python3.10/site-packages/submitit/core/utils.py", line 133, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/mnt/ceph/users/blyo1/projects/LyoSavin2023/core/supplementary-xt_approximation.py", line 50, in generate_samples
    samples_seq_reverse = sequential_posterior_sampler(prior_sampler, manifold_initial_point, M, likelihood_sigma, s, num_cycles=sample_size, eval_at_mean=eval_at_mean, status_bar=True, device=device)[1]
  File "/mnt/ceph/users/blyo1/projects/LyoSavin2023/core/utils/likelihood_utils.py", line 346, in sequential_posterior_sampler
    z_seq = torch.stack(z_seq).detach().numpy().reshape(num_cycles, -1, 2)
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
srun: error: workergpu094: task 0: Exited with exit code 1
